### ISSUE TITLE
Encountering issue while trying to use the app

### ISSUE THREAD

**Issue by Devanshi-Crypto** [dotAadarsh/PaletteAI#1]
![image](https://github.com/dotAadarsh/PaletteAI/assets/76578430/28e99673-75f6-4202-bc10-a4ed97fc8e4e)

**Comment by dotAadarsh** [comment]
Hi @Devanshi-Crypto, 

Due to inactivity, the Supabase instance was paused. I've restored it and fixed a minor issue. You should be able to [access the app](https://paletteai.streamlit.app/) now. Just so you know, generating the result may take some time due to the image processing involved, so please be patient when generating the palette.

Let me know if you encounter any issues or have any feedback.

Thanks,
Aadarsh

**Comment by Devanshi-Crypto** [comment]
Hey @dotAadarsh will definitely check again. Of course such tasks take time while being processed. thanks for updating
